# gitlab-ci

variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=./.m2/repository"
  IMAGE: registry.gitlab.com/nalbam/sample-spring:latest

cache:
  paths:
    - ./.m2/repository

stages:
  - build
  - release

build:
  stage: build
  image: nalbam/builder:alpine
  only:
    - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t $IMAGE .

release:
  stage: release
  image: nalbam/builder:alpine
  only:
    - master
  script:
    - docker push $IMAGE

after_script:
  - ls -alh target
