server:
  port: 8080

spring:
  jackson:
    time-zone: Asia/Seoul
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

app:
  profile: ${PROFILE:default}

slack:
  webhook: ${SLACK_WEBHOOK:https://hooks.slack.com/services/web/hook/token}
  channel: ${SLACK_CHANNEL:sandbox}

message: ${MESSAGE:Refreshed}
