server:
  port: 8080

spring:
  application:
    name: sample-spring
  profiles:
    active: ${PROFILE:default}
  jackson:
    time-zone: Asia/Seoul
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

slack:
  webhook: ${SLACK_WEBHOOK:https://hooks.slack.com/services/web/hook/token}
  channel: ${SLACK_CHANNEL:sandbox}

message: ${MESSAGE:Refreshed}

aws:
  region: ${AWS_REGION:ap-northeast-2}
  access_key: ${AWS_ACCESS_KEY:STRING}
  secret_key: ${AWS_SECRET_KEY:STRING}

logzio:
  token: ${LOGZIO_TOKEN:STRING}

---

spring:
  profiles: default
message: ":tada: Server UP"

---

spring:
  profiles: dev
message: ":tada: Development UP"

---

spring:
  profiles: stage
message: ":tada: Staging UP"

---

spring:
  profiles: prod
message: ":tada: Production UP"
