fullnameOverride: sample-spring

replicaCount: 1

profile: default

namespace: development

image:
  repository: docker-registry.127.0.0.1.nip.io:30500/sample-spring
  tag: latest
  pullPolicy: Always

labels: {}
annotations: {}

pod:
  labels: {}
  annotations: {}

pdb: {}

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations: {}
  labels: {}

ingress:
  enabled: true
  subdomain: sample-spring
  basedomain: 127.0.0.1.nip.io
  hosts: {}
  # hosts:
  #   - sample-spring.opsnow.com
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  labels: {}

autoscaling:
  enabled: false
  min: 1
  max: 5
  cpu: 80
  mem: 80

resources:
  requests:
    cpu: 1000m
    memory: 2048Mi
  # limits:
  #   cpu: 800m
  #   memory: 1252Mi

readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 150
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 150
  periodSeconds: 10
  failureThreshold: 3

# livenessProbe:
#   exec:
#     command:
#     - cat
#     - /tmp/healthy
#   initialDelaySeconds: 15
#   periodSeconds: 10
# livenessProbe:
#   tcpSocket:
#     port: 8080
#   initialDelaySeconds: 15
#   periodSeconds: 10

# hostNetwork: true
# dnsPolicy: Default

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: MESSAGE
    value: "hello world"
  - name: DD_SERVICE_NAME
    value: "sample-spring"
  - name: DD_SERVICE_MAPPING
    value: "cluster_name:seoul-dev-okc1-eks"
  - name: DD_AGENT_HOST
    value: "datadog.monitor.svc.cluster.local"
  - name: DD_TRACE_ANALYTICS_ENABLED
    value: "true"
  - name: DD_TRACE_AGENT_PORT
    value: "8126"
  - name: DD_JMXFETCH_ENABLED
    value: "true"
  - name: DD_JMXFETCH_STATSD_PORT
    value: "8125"
  - name: NEW_RELIC_APP_NAME
    value: "sample-spring"
  - name: POD_NAME
    valueFrom: {fieldRef: {fieldPath: metadata.name}}
  - name: NODE_NAME
    valueFrom: {fieldRef: {fieldPath: spec.nodeName}}

configmap:
  enabled: true
  data:
    MESSAGE: "hello dev world"

secret:
  enabled: true
  data:
    SECRET: "c2VjcmV0IHdvcmxkCg=="
    NEW_RELIC_LICENSE_KEY: "OGYwODMxZGZmMWRhNGNjYTAzYTEwNTU3NTcwNWIxYzVjNzRhM2E3ZQo="
