kind: BuildConfig
apiVersion: v1
metadata:
  name: sample-spring-pipeline
spec:
  type: JenkinsPipeline
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
          stage 'build'
          openshiftBuild(buildConfig: 'sample-spring', showBuildLogs: 'true')
          stage 'deploy'
          openshiftDeploy(deploymentConfig: 'sample-spring')
        }
